### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by iakovmarkov** [lgg/vk-to-telegram-bot#56]
Hey @lgg! First of all thank you for this, it's an incredibly useful little software.
Are you going to continue development of it? I've noticed you had quite a plan for it, and I'm personally missing a few features.
Are you going to go on with the development, or should I fork it?
Thanks!

**Comment by lgg** [comment]
@iakovmarkov unfortunately for now i don't have time to maintain this project. I want to rewrite this project in future with all planed features, because i need this project for my personal usage too. Maybe i will rewrite it from scratch, maybe refactor current one. When it will happen? I don't know :(

So I think it's better to fork it to add features that you need.

**Comment by iakovmarkov** [comment]
@lgg alright, gotcha. I'll either fork this one or use it as a inspiration for something new. PHP isn't my strongest side :)
Thanks, and happy New year!
